# Deployment workflow to Heroku in a Docker container

name: "Build-and-Deploy"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TOKEN:
        description: 'WebCommand API token.'
        required: True
      HEROKU_EMAIL:
        description: 'email used with Heroku app'
        required: true
      HEROKU_API_KEY:
        description: 'API key for Heroku app'
        required: true

jobs:
  build-and-deploy:
    name: docker-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Add API key from secret
        env: 
          TOKEN: ${{ secrets.TOKEN }} 
        run: |
          echo "API_TOKEN=$TOKEN" > config.env

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        run: |
          make prod_build

      - name: Deploy to Heroku
        uses: ./.github/workflows/heroku-deploy.yml
        # secrets:
        #   HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        #   HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

