# Heroku login and deploy workflow
# Requires 
# - GitHub secrets with Heroku credentials
# - Access to the makefile 

name: "Login Heroku and Deploy"

on:
  workflow_call:
    secrets:
      HEROKU_EMAIL:
        description: 'email used with Heroku app'
        required: true
      HEROKU_API_KEY:
        description: 'API key for Heroku app'
        required: true

jobs:
  login-deploy:
    name: login-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Add secrets to config.env for deployment
        env: 
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "HEROKU_EMAIL=$HEROKU_EMAIL" >> config.env
          echo "HEROKU_API_KEY=$HEROKU_API_KEY" >> config.env

      - name: Heroku login 
        run: |
          make heroku_login

      - name: heroku-push
        run: |
          make heroku_push
      
      - name: heroku-release
        run: |
          make heroku_release
