# This CI/CD workflow will test, build a container and deploy the app to Heroku. 

name: "CI/CD Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeql:
    name: codeql
    uses: ./.github/workflows/codeql.yml
  
  tests:
    name:  tests
    uses: ./.github/workflows/test.yml

  deploy:
    name: build and deploy
    needs: [ tests, codeql ]
    uses: ./.github/workflows/build-deploy.yml